services:
  app:
    build: .
    ports:
      - '80:3000'
    environment:
      ROOT_URL: http://3.104.120.177
      MONGO_URL: mongodb://mongo:27017/otk
      PORT: 3000
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
